name: Workflow Blog Post
on:
  schedule:
    # Toutes les heures
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with Last Blog Post
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README with Last Blog Post
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://bigoudops.fr/feed.xml"
          max_post_count: 5
          commit_message: "Update README with latest BigoudOps feed items"
